spring:
  output:
    ansi:
      enabled: DETECT

objects:
  pickup:
    inputBucket: ${PICKUP_BUCKET}
    processingBucket: ${PROCESSING_BUCKET}
    scanInterval: 60
    maxObjectsPerScan: 2
  queue:
    name: objectMessagesQueue

cloud:
  aws:
    region: ${AWS_REGION}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: INFO
    DpFeeder.ProcessingFeeder.messaging.SqsMessageProducer: DEBUG