AWSTemplateFormatVersion: 2010-09-09
Description: Creating DynamoDB tables with CloudFormation
Resources:
  MetadataIndexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dp-MetadataIndex
      AttributeDefinitions:
        - AttributeName: objectID
          AttributeType: S
        - AttributeName: processingDateTime
          AttributeType: S
      KeySchema:
        - AttributeName: objectID
          KeyType: HASH
        - AttributeName: processingDateTime
          KeyType: RANGE
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1