AWSTemplateFormatVersion: "2010-09-09"
Description: "Create SQS Queue with cloudwatch alarms"
Parameters: 
  QueueNameParam:
    Default: "SQS-QUEUE"
    Description: "Name of the SQS Queue to create"
    Type: "String"
Resources: 
  SQSQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName:
        Ref: "QueueNameParam"
Outputs: 
  QueueURL: 
    Description: "URL of new Amazon SQS Queue"
    Value: 
      Ref: "SQSQueue"
  QueueARN: 
    Description: "ARN of new AmazonSQS Queue"
    Value: 
      Fn::GetAtt: 
        - "SQSQueue"
        - "Arn"
  QueueName: 
    Description: "Name of new Amazon SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "SQSQueue"
        - "QueueName"